# Generated by Django 4.0.6 on 2022-07-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=100)),
                ('L_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('User_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=10)),
                ('profile_image', models.ImageField(upload_to='')),
                ('registration_field', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='')),
                ('trailer_field', models.CharField(max_length=100, null=True)),
                ('uploaded_on', models.DateField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finalproject1.user')),
            ],
        ),
        migrations.CreateModel(
            name='favorite_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalproject1.user')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalproject1.movie')),
            ],
        ),
    ]
