# Generated by Django 4.0.6 on 2022-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='main_actors',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
