# Generated by Django 4.0.6 on 2022-08-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject1', '0008_post_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('m_message', models.TextField()),
            ],
        ),
    ]
